apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: mongo-ge
  labels:
    vol: mongo
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/db
