apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: mongo-ge
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    name: mongodb
    targetPort: 27017
  clusterIP: None 
  selector:
    app: mongodb
